### PR TITLE
Cleaned up CICD workflow

### PR DESCRIPTION
**Pull request by AdeoluAdeyemi**
Made some final changes to the CI/CD workflow.

### CODE REVIEW

**Comment by AdeoluAdeyemi** [comment]
#### Terraform Format and Style 🖌`failure`
#### Terraform Initialization ⚙️`success`
#### Terraform Validation 🤖`success`
<details><summary>Validation Output</summary>

```

Success! The configuration is valid.


```

</details>

#### Terraform Plan 📖`success`

<details><summary>Show Plan</summary>

```

terraform
data.aws_iam_role.ecs_task_execution_role: Reading...
aws_ecs_cluster.tf_ecs_cluster: Refreshing state... [id=arn:aws:ecs:eu-west-2:637423624556:cluster/tf_ecs_cluster]
aws_ecr_repository.tf_govuk_fe_wtf_demo_ecr_repo: Refreshing state... [id=tf_govuk_fe_wtf_demo_ecr_repo]
aws_vpc.tf_vpc_main: Refreshing state... [id=vpc-05ba7556d7ccab806]
data.aws_iam_role.ecs_task_execution_role: Read complete after 0s [id=ecsTaskExecutionRole]
aws_ecr_lifecycle_policy.tf_private_ecr_life_pol: Refreshing state... [id=tf_govuk_fe_wtf_demo_ecr_repo]
data.aws_ecr_repository.repo_details: Reading...
data.aws_ecr_repository.repo_details: Read complete after 1s [id=tf_govuk_fe_wtf_demo_ecr_repo]
aws_ecs_task_definition.tf_task_def: Refreshing state... [id=tf_task_def]
aws_subnet.tf_subnet_secondary: Refreshing state... [id=subnet-0b9e4dc94944607d0]
aws_internet_gateway.tf_gw: Refreshing state... [id=igw-0820da94bdf3a35d2]
aws_subnet.tf_subnet_main: Refreshing state... [id=subnet-01eb812afb61ff97b]
aws_security_group.tf_sg_main: Refreshing state... [id=sg-0800164e7a7058908]
aws_lb_target_group.tf_tg_main: Refreshing state... [id=arn:aws:elasticloadbalancing:eu-west-2:637423624556:targetgroup/tf-tg-main/49afcc1d4985c700]
aws_route_table.tf_route_tb: Refreshing state... [id=rtb-0afa72e9ed2f39233]
aws_vpc_security_group_egress_rule.allow_all_traffic_ipv4: Refreshing state... [id=sgr-0f3d6f3f97704fc48]
aws_vpc_security_group_ingress_rule.http: Refreshing state... [id=sgr-0017a2c8c86e9b218]
aws_route_table_association.tf_rtb: Refreshing state... [id=rtbassoc-0b2d50ce20a4be538]
aws_route_table_association.tf_rta: Refreshing state... [id=rtbassoc-0c4113cfdd2e58938]
aws_lb.tf_lb_test: Refreshing state... [id=arn:aws:elasticloadbalancing:eu-west-2:637423624556:loadbalancer/app/tf-lb-test/f45e99607fe277b1]
aws_ecs_service.tf_govuk_service: Refreshing state... [id=arn:aws:ecs:eu-west-2:637423624556:service/tf_ecs_cluster/tf_govuk_service]
aws_lb_listener.front_end: Refreshing state... [id=arn:aws:elasticloadbalancing:eu-west-2:637423624556:listener/app/tf-lb-test/f45e99607fe277b1/e8b34528df1386c2]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

```

</details>

*Pusher: @AdeoluAdeyemi, Action: `pull_request`, Workflow: `Continuous Integration for Python Flask app`*

**Review by evanaukene — APPROVED** [review]
Looks good so far!

**Review by queensley200 — COMMENTED** [review]
this is cool

**Review by queensley200 — APPROVED** [review]
cool

**Pull request merged**
